version: '3.3'

services:
  orderservice:
    container_name: orderservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - orderservice-db

  orderservice-db:
    image: "mysql:8.0"
    container_name: orderservice-db
    environment:
      MYSQL_DATABASE: orders
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
    - "db-data:/var/lib/mysql"
volumes:
  db-data:

