GET http://localhost:8000/api/v1/orders
Accept: application/json

###
POST http://localhost:8000/api/v1/order
Content-Type: application/json

{
  "menuItems": [
    {
      "id": "fjfl-dfjf-rftg-dvgb",
      "quantity": 2
    },
    {
      "id": "abcd-abcd-abcd-abcd",
      "quantity": 1
    }
  ]
}


